name: Provo
version: 1.0
description: A collection of useful commands and functions
author: HAPPYGOPUCKEY
website: http://jakeconley.com
main: com.jakeconley.provo.Provo
commands:
  sorting:
    description: Manage your sorting preferences.
    usage:  See /sorting help for more information.
  sort:
    description: Sort an inventory!  See /sorting help for more information
    usage: /sort (class)
  sortinginfo:
    description: Information about the sorting commands!
    usage: /sortinginfo [page]
  view-notifications:
    description: View your remaining notifications.
    usage: /view-notifications.
  math:
    description: Do some math!
    usage: /math <math query> or /math help
  remind:
    description: Set a reminder for yourself, you'll see it next time you log in.
    usage: /remind <a message for yourself>
  del-reminders:
    description: Acknowledge and delete all of your current reminders.
    usage: /del-reminders
  recipe:
    description: View the recipe of an item.
    usage: /recipe <item name> [page]